### ISSUE TITLE
Skippable Ads

### ISSUE THREAD

**Issue by mustafauysal** [thatguystone/flowplayer-ima#13]
Hi,
Is there any easy way to make ads skippable?

**Comment by anssip** [comment]
Skippable True View ads are now working with this plugin: http://demos.flowplayer.org/adsense/trueview.html

We just released 1.0.2 version of the plugin where these are available.

**Comment by mustafauysal** [comment]
Thanks @anssip 

Is there any example configuration for flash version?

**Comment by bbbo** [comment]
this was a misunderstanding, @anssip was thinking about Flowplayer's own AdSense plugin for FP HTML5 . There is none for FP Flash.

**Comment by mustafauysal** [comment]
@bbbo thanks for clarify.

**Comment by thatguystone** [comment]
Skippable ads are implemented (partially?) in IMA SDK v2, which is what this plugin is based on. They're fully implemented in IMA SDK v3, but I don't really have plans to update this plugin since the last version of FP I even tested it against was 3.2.7. Also, FP seems to be moving away from Flash (as is everyone else), so pretty much what is there is what is there.

You might want to check this out: https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/

**Comment by mustafauysal** [comment]
@thatguystone Thanks for explanation.
